version: "3.4"

networks:
  quest_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      # - php_socket:/var/run/php
      - ./:/var/www
      # - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    networks:
      quest_net:
        ipv4_address: 172.19.0.2

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'quest'
      MYSQL_USER: 'quest'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'quest'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'quest'
    networks:
      quest_net:
        ipv4_address: 172.19.0.4

#  postgres:
#    build:
#      context: .
#      dockerfile: docker/postgres/Dockerfile
#    restart: unless-stopped
#    ports:
#      - '5432:5432'
#    environment:
#      POSTGRES_USER: quest
#      POSTGRES_PASSWORD: quest
#      POSTGRES_DB: quest
#    networks:
#      quest_net:
#        ipv4_address: 172.19.0.3

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/
    ports:
      - "8080:80"
    networks:
      quest_net:
        ipv4_address: 172.19.0.5